#!/usr/bin/env py -3
# -*- coding: utf-8 -*-
"""
Spootfind 产品描述扩充 - 最终版
所有16个产品扩充到 350-400 词
"""

import json
import re
from pathlib import Path

data_path = Path("data/trending.json")
with open(data_path, "r", encoding="utf-8-sig") as f:
    data = json.load(f)

def count_words(text):
    words = re.findall(r'\b\w+\b', text)
    return len(words)

# 完整扩充描述（所有16个产品）
expansions = {
    "t1": """Discover the ultimate pop it fidget toy set for kids and adults, packed with 60 assorted shapes that have taken TikTok by storm. This bulk fidget toy assortment includes circles, squares, hearts, unicorns, dinosaurs, and other trending silhouettes — each one designed to deliver that satisfying pop sensation that keeps fingers busy and minds relaxed. Whether you're sourcing impulse-buy novelties for retail shelves, building a classroom reward box, or stocking a party favor catalog, this set delivers unbeatable variety at a price point that protects your margins. Every piece is molded from food-grade silicone that's odorless, washable, and built to withstand thousands of pops without losing its snap-back elasticity. The toys carry both CE and ASTM F963 certifications, giving wholesale buyers confidence that the product meets stringent safety standards in North America, Europe, and beyond. Manufactured in Shantou Chenghai — China's toy capital with decades of export expertise — this set benefits from mature supply-chain infrastructure, meaning consistent quality and reliable lead times even on large OEM orders. Each shape is pocket-sized (3-6 in.), making it ideal for checkout-counter displays, subscription box inserts, and e-commerce bundle offers. Target markets include the United States, United Kingdom, Germany, Australia, and the Middle East, where fidget and stress-relief toys continue to chart strong search volumes. Custom packaging, private-label printing, and assorted-shape configurations are available on MOQ. Spootfind sources directly from the factory, ensuring you get the best pricing, full compliance documentation, and reliable delivery for your market.""",
    
    "t2": """Elevate your educational toy catalog with this STEM building blocks 500-piece set, engineered for children ages 6 and up who love hands-on construction and creative problem-solving. Fully compatible with all major interlocking brick brands, this kit expands existing collections seamlessly — no awkward fits, no wasted pieces. Beyond standard bricks, the set includes gears, wheels, axles, and connector pieces that let young engineers build working mechanisms: spinning windmills, rolling vehicles, and kinetic sculptures that actually move. It's a STEM learning toy that teaches cause-and-effect, spatial reasoning, and basic mechanical principles without feeling like schoolwork. Certified CE and CPC, the blocks are made from ABS plastic with smooth edges, consistent clutch power, and zero phthalates — meeting the safety benchmarks demanded by distributors in the US, EU, and Australia. Shantou Goworld, the manufacturer, operates an ISO-audited facility with in-house testing labs, so every production run ships with full compliance documentation. The 500-piece count strikes the right balance for retail: substantial enough to feel premium, compact enough for shelf-friendly packaging. Ideal markets include educational suppliers, museum gift shops, e-learning platforms, and toy retailers seeking a high-value STEM construction set that undercuts name-brand pricing without sacrificing quality. OEM color schemes, custom instruction booklets, and branded packaging are available at scale. Spootfind connects you directly with the factory, ensuring competitive pricing, reliable lead times, and full certification support for your target market.""",
    
    "t3": """Meet the remote control stunt car that does it all — 360-degree flips, all-terrain domination, and eye-catching LED light shows that make every run a spectacle. Powered by a responsive 2.4GHz transmitter, this RC stunt vehicle eliminates signal interference so multiple cars can race simultaneously without crossover issues. The dual-sided body design means there is no "right side up" — land on the roof and keep driving. Oversized rubber tires grip grass, gravel, carpet, and pavement with equal confidence, while the rechargeable battery delivers up to 45 minutes of continuous play per charge. FCC and CE certified, the car meets electromagnetic and toy-safety requirements for the US, European, and Australian markets. Shantou Aosheng, the manufacturer, is a veteran RC toy exporter with a dedicated QC team that inspects every batch before shipment. The compact form factor (approximately 25 cm) is perfect for ages 8 and up, and the striking LED underglow makes it a guaranteed eye-catcher on retail shelves and in unboxing videos. Wholesale buyers appreciate the low defect rate, consistent performance, and the ability to order custom frequencies and colorways. Whether you are building an RC toy collection for an e-commerce storefront or supplying brick-and-mortar hobby shops, this stunt car offers a proven best-seller with strong repeat-order rates. Spootfind sources directly from the manufacturer, providing full certification, competitive pricing, and reliable shipping to your market.""",
    
    "t4": """Soft, huggable, and impossible to put down — this 12-inch squishmallow-style plush toy line has become a TikTok sensation and a must-have collectible for kids, teens, and adults alike. Crafted from ultra-soft short-pile plush with a marshmallow-like polyester fill, each character delivers that signature squish that fans cannot stop squeezing. With over 20 unique designs — from sleepy animals to fantasy creatures — the collection encourages repeat purchases and trading, driving higher average order values for retailers. Every plush is EN71 and ASTM F963 certified, ensuring compliance with toy-safety regulations in Europe and North America. The manufacturer, Shantou Miaoji, specializes in character plush and operates a vertically integrated facility covering knitting, stuffing, sewing, and QC under one roof — giving buyers full traceability and consistent quality across production runs. The 12-inch size hits the sweet spot for impulse-buy pricing, gift-basket inclusion, and claw-machine restocking. Key markets include the United States, Canada, UK, Japan, and Australia, where plush collectible trends continue to show strong year-over-year growth in search volume. Social media unboxing videos and "squish" challenges drive organic viral marketing, making this line a proven winner for e-commerce stores, specialty toy retailers, and gift shops. Custom character designs, private-label tags, exclusive colorways, and branded hangtags are available for qualified wholesale orders. Spootfind sources directly from the manufacturer, ensuring competitive pricing, reliable lead times, and full compliance documentation for your target market.""",
    
    "t5": """Unlock creativity and STEM learning with this magnetic tiles 100-piece building set, designed for children ages 3 and up who love constructing 3D structures that sparkle under the light. Each tile features powerful internal magnets with a secure riveted casing — no loose magnets, no pinch points — meeting the rigorous CE and CPC safety standards required by retailers in the US, EU, and Australia. The set includes a balanced mix of squares, triangles, and specialty shapes that let kids build everything from castles and rockets to geometric sculptures. The translucent, high-clarity plastic catches and refracts light, adding a visual wow factor that makes this set a standout on retail shelves and in social media content. Shantou MagWorld, the manufacturer, uses ultrasonic welding and automated magnet placement to ensure consistent quality at scale, with defect rates well below industry average. The 100-piece count is the industry proven sweet spot: enough variety for satisfying builds, compact enough for attractive packaging. Ideal distribution channels include toy stores, online STEM education retailers, Montessori supply catalogs, and gift shops. Parents and educators love the open-ended play value — children develop spatial reasoning, fine motor skills, and creative confidence without screens or batteries. The tiles are fully compatible with major brands, making them an excellent add-on purchase for existing block collections. OEM packaging, custom tile counts (60/120/200), exclusive shape additions, and branded storage boxes are available for volume orders. Spootfind provides factory-direct sourcing with full certification support, helping you bring this proven bestseller to your market with confidence.""",
    
    "t6": """Tap into the booming anime collectibles market with this Japanese-style anime figure blind box series — six standard designs plus one ultra-rare secret chase figure that drives collector excitement and repeat purchases. Each box contains one randomly selected PVC figure standing approximately 8 cm tall, hand-painted with meticulous detail that appeals to serious collectors and casual fans alike. The blind-box format is a proven engagement engine: unboxing videos generate organic social media content, while the secret-chase mechanic boosts sell-through rates and creates trading communities around your product. CE certified and manufactured by Shantou Anime Culture — a studio specializing in anime-licensed merchandise with experience supplying Southeast Asian and Latin American distributors — these figures meet toy-safety standards for the European market. The compact packaging is ideal for retail countertop displays, vending machines, and online subscription-box curation. Target demographics include teens and young adults aged 14-30 in the US, Japan, South Korea, Mexico, and Brazil, where anime fandom continues to drive explosive growth in merchandise spending. Each figure features vibrant colors, durable PVC construction, and a branded display base. The thrill of the "chase" — hunting for the secret design — creates strong word-of-mouth marketing and repeat purchase behavior. Custom character licensing, exclusive regional variants, branded display stands, and countertop display racks are available for qualified partners. Spootfind connects you directly with the studio, ensuring authentic products, competitive pricing, and reliable production schedules for your anime merchandise program.""",
    
    "t7": """Fuel sensory play and early childhood development with this water beads sensory kit, featuring over 50,000 non-toxic polymer beads plus a complete set of fine-motor tools — scoopers, tweezers, sorting cups, and a storage tray. Designed for preschool and kindergarten environments, water beads are one of the fastest-growing categories in educational sensory toys, prized by occupational therapists and Montessori educators for their ability to develop hand-eye coordination, finger strength, and color recognition through open-ended play. The beads expand to approximately 12 mm when hydrated and shrink back for compact storage, making them a practical choice for both classroom and home use. CE and CPC certified, the beads are made from sodium polyacrylate — the same material used in baby diapers — ensuring they are non-toxic and biodegradable. Shantou Oubo, the manufacturer, is a sensory-toy specialist with a clean production record and experience exporting to North American and European educational-supply distributors. The kit format with premium packaging and included accessories differentiates it from bulk-bead commodity listings, supporting higher retail pricing and better margin preservation. Key markets include the US, UK, Germany, and Australia, where sensory-play search volumes have doubled year-over-year. Occupational therapists recommend water beads for children with sensory processing needs, creating a strong word-of-mouth referral network among parents and educators. The beads are reusable, easy to clean, and store compactly when dehydrated. Bulk refill packs, custom tool configurations, branded storage containers, and educational activity guides are available for volume orders. Spootfind sources directly from the manufacturer, providing full safety documentation and reliable supply for your educational toy portfolio.""",
    
    "t8": """Light up playtime with this LED slime making kit that glows in the dark — six vibrant colors of non-toxic PVA-based slime, complete with storage containers, mixing tools, and glow-in-the-dark powder that transforms every batch into a luminescent masterpiece. Slime continues to rank among the top-selling DIY toy categories on Amazon and TikTok, and this kit adds the glow-in-the-dark twist that stands out in search results and unboxing videos. Every component is CE and ASTM F963 certified, meeting toy-safety requirements for North American and European markets. The PVA formula is borax-free and non-sticky, addressing the two most common parent complaints about slime products. Shantou Chenghai-based manufacturing ensures competitive pricing, reliable lead times, and access to China's deepest toy supply chain. The kit format — pre-portioned ingredients plus tools — eliminates the mess and guesswork that frustrate home-made slime attempts, making it a parent-friendly gift choice. Each color comes in its own sealed container, extending shelf life and enabling partial-use play sessions. Ideal retail channels include toy stores, craft supply shops, online STEM and DIY toy retailers, and holiday gift guides. The glow powder additive creates a unique selling proposition that differentiates this kit from standard slime sets, justifying higher retail pricing. Kids love the science-meets-art angle, and parents appreciate the guided activity that doesn't require hunting for ingredients. Custom color palettes, branded packaging, bulk event-pack configurations, and private-label options are available for volume orders. Spootfind provides factory-direct sourcing with full compliance support, helping you capitalize on the slime trend with a differentiated, safety-certified product.""",
    
    "t9": """Power through tight-access excavation jobs with this 1.8-ton mini excavator powered by a proven Kubota diesel engine — the gold standard in compact construction equipment reliability. With a 2.5-meter maximum digging depth and 3.8-meter dumping height, this machine handles trenching, foundation prep, landscaping, and utility work in spaces where full-size excavators simply cannot operate. The compact dimensions allow six units per 40HQ container, dramatically reducing per-unit shipping costs for importers. CE and ISO 9001 certified, the excavator meets European machinery directives and global quality-management standards, opening doors to government tenders and regulated markets. Key features include pilot-operated hydraulic controls for smooth, precise operation; a retractable undercarriage that narrows from 1,500 mm to 1,000 mm for passage through gates and doorways; and a reinforced boom designed for heavy-duty digging cycles. Jining's construction-equipment cluster provides unmatched aftermarket support: spare parts ship within 48 hours, and the standard Kubota engine means filters and service items are available worldwide. Target markets include Australia's booming residential-construction sector, the EU's urban-renovation market, and North American landscaping contractors seeking a cost-competitive alternative to Japanese and Korean brands. The 1.8-ton class is the sweet spot for small-scale contractors who need digging power without the logistics overhead of full-size equipment. OEM branding, custom paint, ROPS/FOPS cab options, and auxiliary hydraulic circuits are available for volume orders. Spootfind sources directly from the manufacturer, providing full technical documentation, spare parts lists, and after-sales support to keep your customers operating.""",
    
    "t10": """Compact, powerful, and purpose-built for small-site compaction — this 3-ton single-drum road roller with hydraulic drive delivers professional-grade results on bike paths, driveways, parking lots, and pipeline trench backfill. The 0.8-meter drum width strikes the optimal balance between coverage and maneuverability, while the 3.2-ton centrifugal force ensures deep-density compaction in fewer passes — saving fuel, time, and operator hours on every job. Hydraulic propulsion provides smooth, stepless speed control from 0-8 km/h, with instant forward and reverse for efficient turnarounds in confined spaces. CE certified and manufactured in Jining — one of China's largest construction-machinery hubs — this roller benefits from a mature supply chain that keeps component costs low and spare-parts availability high. The operator platform features vibration-dampened controls, an adjustable seat, and 360-degree visibility, meeting ergonomic and safety requirements for European and Australian job sites. At just 3 tons operating weight, the machine can be transported on a standard flatbed trailer without oversized-load permits, reducing mobilization costs. Key markets include municipal public-works departments, landscaping contractors, and rental-fleet operators seeking a reliable compaction solution at a fraction of the price of European brands. The hydraulic drive system eliminates belt maintenance and provides better hill-climbing capability than mechanical-drive alternatives. OEM options, ROPS canopy, diesel/LPG engine variants, and water-spray systems are available. Spootfind connects you directly with the manufacturer, ensuring competitive pricing, full certification documentation, and reliable after-sales support for your equipment business.""",
    
    "t11": """Pour concrete with confidence using this 350L diesel concrete mixer, engineered for small construction sites, DIY home projects, and rental fleet operations. With a 350-liter drum capacity and 280-liter mixing capacity, this machine delivers consistent, lump-free concrete batch after batch — the workhorse every contractor needs on site. The diesel engine provides reliable power without dependence on electric outlets, making it ideal for remote job sites and outdoor pours. CE certified and manufactured in Jining — China's premier construction machinery hub — this mixer benefits from mature supply chain infrastructure, competitive component pricing, and experienced assembly technicians. The heavy-duty steel frame and pneumatic tires handle rough terrain, while the tilting drum mechanism allows precise pour control. Safety features include a drum guard, emergency stop switch, and overload protection. Contractors appreciate the 15-20 minute mix cycle that keeps projects moving, while rental operators value the simple controls that don't require extensive operator training. The 350L capacity hits the sweet spot for residential foundations, sidewalk repairs, fence post sets, and small commercial slabs. Spare parts availability is excellent thanks to the standard diesel engine and commodity components. Target markets include Australia's booming residential construction sector, Southeast Asia's infrastructure development, and North American equipment rental companies seeking cost-competitive alternatives to premium brands. OEM branding, custom paint colors, electric-start options, and water pumps are available for volume orders. Spootfind sources directly from the manufacturer, providing full technical documentation, spare parts lists, and after-sales support to keep your customers operating.""",
    
    "t12": """Lift smart, lift safe with this 5-ton truck-mounted mini crane — the compact lifting solution for delivery trucks, small construction sites, and workshop material handling. With a 5-ton maximum lifting capacity and 8-meter maximum reach, this crane handles steel bars, concrete pipes, lumber, and equipment with confidence. The hydraulic boom features multiple extension sections for precise load placement, while the 360-degree continuous rotation ensures you can position loads exactly where needed. CE certified and manufactured in Jining — China's construction machinery production base — this crane benefits from rigorous factory testing, certified structural steel, and reliable hydraulic components. The truck-mounted design eliminates the need for a separate transport trailer, reducing logistics costs and enabling on-site mobility. Key features include a wired remote control for safe operation away from the load, automatic overload protection, and a hydraulic outrigger system for stable operation on uneven ground. Target markets include building material suppliers, equipment rental companies, and contractors in Australia, Southeast Asia, the Middle East, and Africa — regions where small-scale construction and delivery operations dominate. The 5-ton capacity class is the proven sweet spot for delivery-truck integration, providing serious lifting power without exceeding standard truck payload limits. OEM branding, custom boom lengths, wireless remote options, and certification packages for different markets are available. Spootfind sources directly from the manufacturer, ensuring competitive pricing, full certification documentation, and reliable after-sales support for your lifting equipment business.""",
    
    "t13": """Move earth, move snow, move everything with this 0.8-ton skid steer loader — the most versatile compact machine for landscaping, construction, and property maintenance. With a 0.8-ton operating capacity and universal quick-attach plate, this machine accepts dozens of attachments: augers, trenchers, brush cutters, snow blowers, pallet forks, and more — transforming from one machine into an entire fleet. The compact dimensions (under 1 meter wide) allow access through standard doorways and gates, making it ideal for indoor demolition, barn cleanup, and tight-access landscaping. CE certified and manufactured in Jining's construction equipment cluster, this skid steer benefits from mature supply chain infrastructure, reliable hydraulic components, and excellent spare parts availability. Key features include pilot-operated joystick controls for intuitive operation, a ROPS/FOPS-certified cab for operator safety, and a maintenance-friendly design with ground-access service points. The 0.8-ton class is the proven entry point for small contractors, property owners, and rental fleets — big enough to do real work, small enough to transport on a standard trailer. Target markets include Australia's landscaping sector, North American equipment rental companies, and European municipal public-works departments. The universal attachment plate means your customers can use existing implements, reducing total cost of ownership. OEM branding, enclosed cab options, auxiliary hydraulics, and LED lighting packages are available for volume orders. Spootfind connects you directly with the manufacturer, providing full technical documentation, spare parts support, and after-sales service to keep your customers productive.""",
    
    "t14": """Build your dream diecast construction fleet with this 1:50 scale excavator model set (6-pack), featuring precision-machined metal components, authentic paint schemes, and functional hydraulic simulation that moves like the real machine. Each model in the set represents a different excavation specialist — standard excavator, long-reach excavator, demolition excavator, amphibious excavator, compact excavator, and mini excavator — giving collectors and retailers a complete construction fleet in one SKU. The diecast metal body and plastic components are built to 1:50 scale precision, with authentic Caterpillar-style livery, realistic hydraulic lines, and a rotating cab that actually turns. Collectors display these on desks, in cabinets, and at trade show booths — they're conversation starters that showcase construction machinery appreciation. CE certified and manufactured by Shantou Diecast Pro, a specialist in precision diecast miniatures with export experience to Europe, North America, and Australia. The 6-pack format encourages repeat purchases (collect them all!) and creates strong gift potential for construction enthusiasts, equipment operators, and their families. The models are packaged in a display-friendly window box that shows all six units, making it an eye-catching retail shelf presence. Target markets include construction equipment dealerships (for promotional gifts), heavy equipment trade shows, model hobby shops, and online diecast collector communities. The 1:50 scale is the industry standard for construction diecast, ensuring compatibility with existing display cases and collector shelves. Custom branding, OEM packaging, corporate gift configurations, and exclusive color schemes are available for qualified orders. Spootfind connects you directly with the manufacturer, ensuring authentic products, competitive pricing, and reliable delivery for your diecast program.""",
    
    "t15": """Finish concrete like a pro with this 36-inch power trowel, engineered for professional contractors who demand flawless, mirror-smooth concrete surfaces on every pour. The 36-inch finishing diameter strikes the optimal balance between productivity and maneuverability, handling driveways, patios, garage slabs, and small commercial floors with equal confidence. Powered by a reliable Honda-engine clone (170F series), this trowel delivers consistent RPM under load, ensuring uniform finish quality across the entire slab. The heavy-duty steel blades are precision-balanced and replaceable, with a tilt-up design that allows fine adjustment of the finishing angle for everything from initial floating to high-gloss burnishing. CE certified and manufactured in Jining's construction-equipment cluster, this power trowel benefits from rigorous factory testing, durable powder-coat finish, and readily available replacement blades and engine parts. Contractors appreciate the folding handle that reduces transport width for pickup truck beds and the vibration-dampened grip that reduces operator fatigue during long pours. Target markets include professional concrete contractors, rental equipment companies, and DIY enthusiasts in Australia, North America, Europe, and Southeast Asia. The 36-inch size is the proven industry standard for residential and light commercial work — large enough to be productive, compact enough for tight-access pours. OEM branding, electric-start options, ride-on trowel variants, and blade kits are available for volume orders. Spootfind sources directly from the manufacturer, providing full technical documentation, spare parts lists, and after-sales support to keep your customers finishing perfectly.""",
    
    "t16": """Haul heavy loads across rough terrain with this 500kg tracked mini dumper — the compact material handler that goes where wheelbarrows and pickup trucks cannot. With a 500kg payload capacity and narrow 70cm track width, this machine accesses garden gates, backyard pathways, and interior job sites with ease, while the steel tracks provide excellent traction on mud, gravel, grass, and stairs. The diesel engine delivers reliable power with excellent fuel economy, while the hydraulic tipping system lets you dump loads without manual lifting — protecting your operators from strain and injury. CE certified and manufactured in Jining's construction-machinery hub, this mini dumper benefits from a robust steel frame, sealed bearings, and a simple mechanical design that keeps maintenance costs low. Key features include a pivoting dump body that empties completely, a locking parking brake for safety on slopes, and a comfortable operator platform with intuitive controls. Target markets include landscaping contractors, rental equipment companies, and municipal public-works departments in Australia, the UK, Europe, and North America. The 500kg capacity class is the sweet spot for landscapers and small contractors — substantial enough for real work, compact enough for easy transport. OEM branding, enclosed cargo boxes, hydraulic winch options, and road-legal trailer kits are available for volume orders. Spootfind connects you directly with the manufacturer, ensuring competitive pricing, full certification documentation, and reliable after-sales support for your material-handling equipment business."""
}

# 应用扩充
updated = 0
for prod in data['products']:
    tid = prod['id']
    if tid in expansions:
        old_words = count_words(prod.get('seoDescription', ''))
        prod['seoDescription'] = expansions[tid].strip()
        new_words = count_words(prod['seoDescription'])
        print(f"✅ {tid} {prod['name']}: {old_words} → {new_words} words")
        updated += 1
    else:
        words = count_words(prod.get('seoDescription', ''))
        print(f"⚠️  {tid} {prod['name']}: already {words} words")

if updated > 0:
    with open(data_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=4)
    print(f"\n✅ Updated {updated} products, saved to {data_path}")
else:
    print("\nℹ️  No products needed updating")

print("\nDone!")
